### ISSUE TITLE
Variable names ending with an apostrophe are not parsed correctly by GeSHi syntax highlighter

### ISSUE THREAD

**Issue by jhenligne** [ppelleti/haskell-wiki-bugs#8] opened 2017-02-06 17:18 UTC
GeSHi is quite old (last version is date August 2012).
Newer syntax highlighter could improve code readability and correct error mentioned in the title.

As an example, here is how a sample of [example 12](https://wiki.haskell.org/All_About_Monads#Example_3) in [All About Monads](https://wiki.haskell.org/All_About_Monads) looks like now:
<img width="625" alt="geshi" src="https://cloud.githubusercontent.com/assets/22025034/22652502/59d26c8a-ec8f-11e6-86bd-783258ad5b28.png">

And how it could look like with another library, [Prism](http://prismjs.com/) in that case:
<img width="599" alt="prism" src="https://cloud.githubusercontent.com/assets/22025034/22652553/8b21b570-ec8f-11e6-97d5-7a119b14af89.png">

It is also worth noting GeSHi is a PHP library while Prism is written in JavaScript.
Prism inclusion in HTML code is very lightweight compared to GeSHi which add formatting `<span>` tags everywhere, as a result HTML pages would be lighter, even with css and js files included.

**Comment by jhenligne** [comment] 2017-02-06 20:30
Arf! I should have read previous Issues as I just realize this bug was described in Issue #6...

Nevertheless it may be a chance because following another lead drove me to realize how verbose is the SyntaxHighlight extension of MediaWiki.

Comparing HTML produced by it on [Extension:SyntaxHighlight](https://www.mediawiki.org/wiki/Extension:SyntaxHighlight) page with the use of [Prism library](http://prismjs.com/) is enlightening.

On [Usage](https://www.mediawiki.org/wiki/Extension:SyntaxHighlight#Usage) subtitle here is the Python code example (HTML):

&lt;div class="mw-highlight mw-content-ltr" dir="ltr">
&lt;pre>&lt;span class="lineno">1 &lt;/span>&lt;span class="k">def&lt;/span> &lt;span class="nf">quickSort&lt;/span>&lt;span class="p">(&lt;/span>&lt;span class="n">arr&lt;/span>&lt;span class="p">):&lt;/span>
&lt;span class="lineno">2 &lt;/span>	&lt;span class="n">less&lt;/span> &lt;span class="o">=&lt;/span> 
&lt;span class="p">[]&lt;/span>
&lt;span class="lineno">3 &lt;/span>	&lt;span class="n">pivotList&lt;/span> &lt;span class="o">=&lt;/span> &lt;span class="p">[]&lt;/span>
&lt;span class="lineno">4 &lt;/span>	&lt;span class="n">more&lt;/span> &lt;span class="o">=&lt;/span> &lt;span class="p">[]&lt;/span>
&lt;span class="lineno">5 &lt;/span>	&lt;span class="k">if&lt;/span> &lt;span class="nb">len&lt;/span>&lt;span class="p">(&lt;/span>&lt;span class="n">arr&lt;/span>&lt;span class="p">)&lt;/span> &lt;span class="o">&lt;=&lt;/span> &lt;span class="mi">1&lt;/span>&lt;span class="p">:&lt;/span>
&lt;span class="lineno">6 &lt;/span>		&lt;span class="k">return&lt;/span> &lt;span class="n">arr&lt;/span>
&lt;span class="lineno">7 &lt;/span>	&lt;span class="k">else&lt;/span>&lt;span class="p">:&lt;/span>
&lt;span class="lineno">8 &lt;/span>		&lt;span class="k">pass&lt;/span>
&lt;/pre>&lt;/div>

Equivalent display with Prism (HTML):
&lt;pre class="line-numbers">&lt;code class="language-python">
def quickSort(arr):
	less = []
	pivotList = []
	more = []
	if len(arr) <= 1:
		return arr
	else:
		pass
  &lt;/pre>&lt;/code>

Notice how similar is MediaWiki markup (HTML):
&lt;syntaxhighlight lang="python" line='line'>
def quickSort(arr):
	less = []
	pivotList = []
	more = []
	if len(arr) <= 1:
		return arr
	else:
		pass
&lt;/syntaxhighlight>

I don't know how risky it is to update MediaWiki and I don't know if it is possible to hack it to use an external library like Prism but it may be a cheaper fix.

**Comment by ppelleti** [comment] 2017-02-08 08:25
I think the easiest, lowest-risk approach would be to update to the last version of GeSHi, which has fixed this problem.  I will try to look into that soon.

Long-term, when #7 is fixed, we'll be using Pygments, which also has fixed this problem.

I don't think switching to a third syntax highlighter, other than GeSHi or Pygments, is going to be attractive unless it already has a MediaWiki plug-in, because I'd like to avoid maintaining custom code.  I'd rather use MediaWiki "out of the box" as much as possible, because this will make maintenance easier.

Meanwhile, I'm going to close this bug, since it is a duplicate of #6, which is still open.

**Closed by ppelleti** 2017-02-08 08:25 UTC
